// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizGameServer.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(QuizGameDbContext))]
    [Migration("20250903005932_QuizResults")]
    partial class QuizResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuizContents");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizContentQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizContentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizContentId");

                    b.ToTable("QuizContentQuestions");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("QuizContentId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.SharedQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizContentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizContentId");

                    b.ToTable("SharedQuizzes");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizContentQuestion", b =>
                {
                    b.HasOne("QuizGameServer.Domain.Entities.QuizContent", "QuizContent")
                        .WithMany("Questions")
                        .HasForeignKey("QuizContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizContent");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizResult", b =>
                {
                    b.HasOne("QuizGameServer.Domain.Entities.QuizContent", "QuizContent")
                        .WithMany()
                        .HasForeignKey("QuizContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizContent");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.SharedQuiz", b =>
                {
                    b.HasOne("QuizGameServer.Domain.Entities.QuizContent", "QuizContent")
                        .WithMany()
                        .HasForeignKey("QuizContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizContent");
                });

            modelBuilder.Entity("QuizGameServer.Domain.Entities.QuizContent", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
